---
title: Module One Retrospective
description: "Review content in the first module"
date: 2025-09-29
layout: full
toc: true
toc-expand: 3
---

## Activities

- {{< iconify fa6-solid people-line size=18px >}} **Tuesday**:
  - No new material due since it is the last week of the module
  - Teams one, two, and three give retrospective presentations
  - No new slides needed for this retrospective presentation
  - Retrospective topics should be reserved in prior week
- {{< iconify fa6-solid gears size=18px >}} **Tuesday Laboratory**:
  - Knowledge-checks rescheduled from Week Five
  - Students take the executable examination for module one
  - Examination's focus is on the problems that are:
    - Computable
    - Tractable
    - Restricted versions of problems that are:
      - Undecidable
      - Intractable
- {{< iconify fa6-solid people-line size=18px >}} **Thursday**:
  - No new material due since it is the last week of the module
  - Teams four, five, and six give retrospective presentations
  - No new slides needed for this retrospective presentation
  - Retrospective topics should be reserved in prior week
