---
title: "Applying Turing Reductions"
description: "Explore a new way to prove uncomputability"
date: 2025-10-13
layout: full
toc: true
toc-expand: 3
---

## Activities

- {{< iconify fa6-solid lightbulb size=18px >}} **Reading Assignment**:
  - Chapter seven of [What Can be Computed? A Practical Guide to the
  Theory of Computation](https://whatcanbecomputed.com/)
- {{< iconify fa6-solid lightbulb size=18px >}} **Monday**:
  - No presentations slides due since start of new module
- {{< iconify fa6-solid people-line size=18px >}} **Tuesday**:
  - Instructor's presentation on this week's assigned topics
- {{< iconify fa6-solid gears size=18px >}} **Tuesday Laboratory**:
  - No new presentations during the laboratory session
  - Complete these tasks during the laboratory session:
    - Make sure that you have created all GitHub repositories
    - Make token requests as needed for work in module one
    - Complete all remaining work from module one
    - Read all content in the current chapter to grasp fully
    - Prepare for the interactive discussion session on Thursday
- {{< iconify fa6-solid people-line size=18px >}} **Thursday**:
  - Instructor's presentation on this week's assigned topics
  - Charette session where students collaboratively ask and answer questions

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weekeight/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week
Eight: Turing Reductions](../../slides/weekeight/)
