---
title: Slides
layout: full
toc: true
listing:
  - id: featured-presentations
    type: default
    sort-ui: true
    filter-ui: true
    fields: [date,title,description]
    field-display-names:
      description: "Question"
    contents:
      - "week*/**/*.qmd"
      - "!teams"
    sort:
      - "date"
      - "title"
      - "description"
  - id: teams-presentations
    type: default
    sort-ui: true
    filter-ui: true
    fields: [date,title,description]
    field-display-names:
      description: "Question"
    contents:
      - "teams*/**/*.qmd"
    sort:
      - "date"
      - "title"
      - "description"
---

## Course Presentations

Interesting in learning more about the theory of computation? Checkout these
slide decks to learn more! Each deck explores topics in Python programming and
theoretical machines. Finally, make sure to review the [course
schedule](../schedule/index.qmd) and the [course
syllabus](../syllabus/index.qmd) for more details about how these slides connect
to various course projects and the content in the textbook called [What Can be
Computed](https://whatcanbecomputed.com/). Importantly, the material in these
course slides is derived from and inspired by the content in and companion
slides for the textbook [What Can be
Computed](https://whatcanbecomputed.com/).

:::{#featured-presentations}
:::

## Team Presentations

Interesting in learning more about the theory of computation from the
perspective of students who are exploring the topic? Checkout these slide decks
to learn more! While these slides are not guaranteed to be correct, they should
show the growth of a learner as they develop their knowledge and skills as a
proofgrammer.

:::{#team-presentations}
:::
