---
title: Equipping Proofgrammers
description: "Ensure Success in Theorectical Machines"
date: 2025-08-25
layout: full
toc: true
toc-expand: 3
---

## Activities

- {{< iconify fa6-solid lightbulb size=18px >}} **Monday**:
  - No class due to the fact that the semester has not started yet
- {{< iconify fa6-solid people-line size=18px >}} **Tuesday**:
  - Introductions and course overview for theoretical machines
  - As outlined in the [syllabus](../../syllabus/index.qmd), teams give two
  types of presentations:
     - Proofgrammer presentations during first three weeks of module
     - Retrospective presentations during the last week of a module
- {{< iconify fa6-solid gears size=18px >}} **Tuesday Laboratory**:
  - Installation of required software tools for proofgramming
  - Release the schedule for next week's team-based presentations
  - Teams meet to confirm contact information and plan their presentations
- {{< iconify fa6-solid gears size=18px >}} **Thursday**:
  - Continued introduction to topics in theoretical machines
  - Teams work on their presentations due next week on Monday
  - Confirm the creation of the following deliverables:
    - A presentation slide deck using [Quarto](https://quarto.org/) and
    [RevealJS](https://revealjs.com/)
    - A stand-alone Python program program fully managed by
    [uv](https://docs.astral.sh/uv/)
  - All content available in the designated directory of the course website

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weekone/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week One:
Introduction to Theoretical Machines](../../slides/weekone/)
