---
title: "Grasping Universal Computation"
description: "Create and Use Universally Powerful Programs"
date: 2025-10-06
layout: full
toc: true
toc-expand: 3
---

## Activities

- {{< iconify fa6-solid lightbulb size=18px >}} **Reading Assignment**:
  - Chapter six of [What Can be Computed? A Practical Guide to the
  Theory of Computation](https://whatcanbecomputed.com/)
- {{< iconify fa6-solid lightbulb size=18px >}} **Monday**:
  - Fall break means that there is no class on Thursday
- {{< iconify fa6-solid people-line size=18px >}} **Tuesday**:
  - Review of presented material about Turing machines
  - Instructor's presentation on this week's assigned topics
  - Highlights for content from week eight of the course
- {{< iconify fa6-solid gears size=18px >}} **Tuesday Laboratory**:
  - No new presentations during the laboratory session
  - Make sure that you have created all GitHub repositories
  - Make token requests as needed for work in module one
  - Complete all remaining work from module one
- {{< iconify fa6-solid people-line size=18px >}} **Thursday**:
  - No class due to fall break starting on Thursday morning
  - All new material covered during class session on Tuesday

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weekseven/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week
Seven: Universal Computer Programs](../../slides/weekseven/)
