---
title: "Exploring Nondeterminism"
description: "Nondeterminism does not change computability"
date: 2025-10-20
layout: full
toc: true
toc-expand: 3
---

## Activities

- {{< iconify fa6-solid lightbulb size=18px >}} **Reading Assignment**:
  - Chapter eight of [What Can be Computed? A Practical Guide to the
  Theory of Computation](https://whatcanbecomputed.com/)
- {{< iconify fa6-solid lightbulb size=18px >}} **Monday**:
  - No presentations slides needed yet due to schedule changes
- {{< iconify fa6-solid people-line size=18px >}} **Tuesday**:
  - Instructor's presentation on this week's assigned topics
- {{< iconify fa6-solid gears size=18px >}} **Tuesday Laboratory**:
  - No new presentations during the laboratory session
  - Complete these tasks during the laboratory session:
    - Participate in an extra charette session
    - Prepare for the standard charette session on Thursday
    - Start working on the presentations for next week
    - Read all content in the current chapter to grasp fully
- {{< iconify fa6-solid people-line size=18px >}} **Thursday**:
  - Instructor's presentation on this week's assigned topics
  - Charette session where students collaboratively ask and answer questions

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weeknine/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week
Nine: Exploring Nondeterminism](../../slides/weeknine/)
