---
title: "Exploring Turing Machines"
description: "Create and Use Simple Computers"
date: 2025-09-22
layout: full
toc: true
toc-expand: 3
---

## Activities

- {{< iconify fa6-solid lightbulb size=18px >}} **Reading Assignment**:
  - Chapter five of [What Can be Computed? A Practical Guide to the
  Theory of Computation](https://whatcanbecomputed.com/)
- {{< iconify fa6-solid lightbulb size=18px >}} **Monday**:
  - No new presentation slides due for this week
- {{< iconify fa6-solid people-line size=18px >}} **Tuesday**:
  - Instructor's presentation on this week's assigned topics
  - Review of the format for knowledge checks
- {{< iconify fa6-solid gears size=18px >}} **Tuesday Laboratory**:
   - *Knowledge-checks*:
      - Approximately five-minute interviews completed in random order
      - Knowledge-check focuses on key concepts explained during module
      - Rescheduled to Week Six due to the course instructor's absence
   - *Retrospective Presentations*:
      - Instructor assigns teams for the retrospective presentations
      - Teams pick and present their own topics on this module's content
      - Teams collaboratively complete their retrospective presentations
      - Team-based presentations occur next week on Tuesday and Thursday
- {{< iconify fa6-solid people-line size=18px >}} **Thursday**:
  - Instructor's presentation on this week's assigned topics
  - Charette session where students collaboratively ask and answer questions

## Slides

```{=html}
<iframe class="slide-deck" src="../../slides/weekfive/"></iframe>
```

{{< iconify majesticons presentation-play size=18px >}} Full Screen: [Week Five:
Turing Machines](../../slides/weekfive/)
