"""Detecting unused variables from Python input files."""
import ast



def read_file():
    """Read a Python input file."""

    with open("uv.py", "r") as fn:
        read_fn = fn.read()
    parser = ast.parse(read_fn)
    create_ast = ast.dump(parser, indent=4)
    return create_ast

def store_ast():
    """Store the input file and convert it to an AST."""

    ast_tree = read_file()

    with open("ast.txt", "w", encoding='utf-8') as fn:
        write_fn = fn.write(ast_tree)

    return write_fn


def detect_unused_variables():
    """Detect unused variables from using the AST generated by store_ast()"""

    with open("ast.txt", "r", encoding='utf-8') as fn:
        lines = fn.readlines()

    for line in lines:
        split_lines = line.strip()
        word = "'limit'"

        if word in split_lines:
            count_word = word.count("'limit'") # I only look for a specific word

            if count_word == 1:
                print(f"We found an unused variable: {word}")
            else:
                print("The file you have provided does not have unused variables!")



if __name__ == "__main__":
    detect_unused_variables()
